/*
 * abc.java
 *
 * Created on ३ दिसंबर, २००५, १०:०५ पूर्वाह्न
 */

/**
 *
 * @author  Nitin Kumar
 */
public class abc extends javax.swing.JInternalFrame {
    
    /** Creates new form abc */
    public abc() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        pack();
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
