SET TALK OFF
CLOSE ALL
USE STUDENT

ANS = "Y"

DO WHILE(ANS != "N")
	CLEAR
	DT = {}
	STORE 0 TO RL
	STORE SPACE(20) TO NM
	@ 5,20 SAY "ENTER FOLLOWING DETAILS OF THE STUDENT"
	@ 8,10 SAY "ENTER ROLL NO. : " GET RL
	@ 9,10 SAY "ENTER NAME :" GET NM
	@ 10,10 SAY "ENTER DATE OF BIRTH" GET DT 
	READ
	
	LOCATE FOR ROLLNO = RL
	
	IF FOUND()
		@ 12,15 SAY "DUPLICATE ROLL NO : ENTER UNIQUE"		
	ELSE
		APPEND BLANK 
		REPLACE NAME WITH NM, ROLLNO WITH RL, DT_O_BIRTH WITH DT
	ENDIF
	
	@ 15,10 SAY " DO U WANT TO CONTINUE " GET ANS
	READ
	ANS = UPPER(ANS)
ENDDO

CLOSE ALL
