*1.	  Write a FOXPRO program to find the area of rectangles. 
*   Program should continue till user's request.

SET TALK OFF 
CLEAR

STORE "Y" TO ANS

DO WHILE (ANS = "Y")
	CLEAR
	STORE 0 TO LENGTH,BREADTH,AREA
	
	@ 10,10 SAY [ENTER THE DIMENSIONS OF THE RECTANGLE   :]
	@ 11,60	SAY [LENGTH   :] GET LENGTH
	@ 12,60 SAY [BREADTH:] GET BREADTH
	READ
	
	AREA = LENGTH * BREADTH
	
	@ 15,10 SAY [AREA OF THE RECTANGLE FOR GIVEN DIMENSIONS = ] + STR(AREA)
	
	@ 20,10 SAY [DO YOU WANT TO CONTINUE(Y/N)] GET ANS
	READ
	ANS= UPPER(ANS)
ENDDO	

SET TALK ON 
RETURN 
	 