SET TALK OFF
CLEAR
USE STUDENT
RLL = 0

@ 10,10 SAY "ENTER ROLL NO. OF THE STUDENT U WANT TO SEE DETAIL" GET RLL
READ

LOCATE FOR ROLLNO = RLL

IF FOUND()
	@ 15,20 SAY "DETAILS OF THE STUDENT WITH THE GIVEN ROLL NO"
	@ 17,10 SAY "NAME OF THE STUDENT :" + ALLTRIM(NAME)
	@ 18,10 SAY "DATE OF BIRTH : " + DTOC(DT_O_BIRTH)
ELSE
	@ 15,20 SAY "SPECIFIED ROLL NOT FOUND"
ENDIF

CLOSE ALL
