SET TALK OFF
CLEAR
USE STUDENT 
SET CENTURY ON
CLEAR
R = 45
REC = 1

DO WHILE .NOT. EOF()
	IF (R >= 25)
		IF (R <> 45) 
			READ
			CLEAR
		ENDIF
		@ 2,8 TO 33,85 
		@ 3,27 SAY "CONTENTS OF STUDENT TABLE" FONT"",10 STYLE "B"
		@ 4,8 TO 4,85
		@ 5,9 SAY "RECORD NO." STYLE "B" FONT"",8
		@ 5,24 SAY "ROLL NO." STYLE "B" FONT"",8
		@ 5,45 SAY "NAME" STYLE "B" FONT"",8
		@ 5,67 SAY "DATE OF BIRTH" STYLE "B" FONT"",8
		@ 6,8 TO 6,85
		R = 1		
	ENDIF
	
	@ (6 + R),15 SAY "" + ALLTRIM(STR(REC)) STYLE "B" FONT"",8
	@ (6 + R),25 SAY "" + ALLTRIM(STR(ROLLNO))FONT"",8
	@ (6 + R),40 SAY "" + ALLTRIM(NAME) FONT"",8
	@ (6 + R),70 SAY "" + DTOC(DT_O_BIRTH) FONT"",8
	SKIP
	R = R + 1
	REC = REC + 1
ENDDO

CLOSE ALL
