SET TALK OFF
CLEAR

DIME ARR[10]
STORE SPACE(20) TO ARR
STORE 0 TO NOOFELE

@ 5,10 SAY "ENTER NO OF ELEMENTS IN THE ARRAY" GET NOOFELE
READ

@ 7,10 SAY "ENTER THE ELEMENTS OF THE ARRAY  : "
R = 9
FOR I = 1 TO NOOFELE 
	@ R,15 SAY "ELEMENT NO : " + ALLTRIM(STR(I)) + " : " GET ARR(I)
	READ
	R = R + 1
NEXT I

@ R,10 SAY "THE ELEMENTS OF THE ARRAY ENTERED BY THE USER : "
FOR I = 1 TO NOOFELE 
	R = R + 1
	@ R,15 SAY "ELEMENT NO : " + ALLTRIM(STR(I)) + " : " + ALLTRIM(ARR(I))
NEXT I

FOR I = 1 TO NOOFELE/2
	TEMP = ARR(I)
	ARR(I) = ARR(NOOFELE - I + 1)
	ARR(NOOFELE - I + 1) = TEMP
NEXT I

@ R,10 SAY "THE ELEMENTS OF THE ARRAY AFTER REVERSING : "
FOR I = 1 TO NOOFELE 
	R = R + 1
	@ R,15 SAY "ELEMENT NO : " + ALLTRIM(STR(I)) + " : " + ALLTRIM(ARR(I))
NEXT I
